# code: language=ansible
- name: Basic Setup
  tags: basic
  hosts: all
  roles:
    - basic

- name: Trader Setup
  tags: setup_trader
  hosts: trader
  roles:
    - reset_trader
    - setup_trader

- name: Reset Trader
  tags: reset_trader
  hosts: trader
  roles:
    - reset_trader

- name: Reset Center
  tags: reset_center
  hosts: center
  roles:
    - reset_center
