# code: language=ansible
- name: Basic
  tags: basic
  hosts: vms
  roles:
    - basic

- name: Reboot
  tags: reboot
  hosts: vms
  roles:
    - reboot

- name: Remove_all_container
  tags: reset_all
  hosts: vms
  roles:
    - remove_all_container

- name: Apply_cert
  tags: apply_cert
  hosts:
    - trader
    - mail
  vars_files:
    - group_vars/vars.yml
  roles:
    - remove_all_container
    - apply_cert
    - remove_all_container

- name: Init_mail
  tags: init_mail
  hosts: mail
  vars_files:
    - group_vars/vars.yml
  roles:
    - remove_all_container
    - init_mail

- name: Setup_mail
  tags: setup_mail
  hosts: mail
  vars_files:
    - group_vars/vars.yml
  roles:
    - remove_all_container
    - setup_mail

- name: Reset_mail
  tags: reset_mail
  hosts: mail
  roles:
    - remove_all_container

- name: Setup_blog
  tags: setup_blog
  hosts: blog
  vars_files:
    - group_vars/vars.yml
  roles:
    - remove_all_container
    - build_wordpress
    - remove_all_container
    - setup_blog

- name: Reset_blog
  tags: reset_blog
  hosts: blog
  roles:
    - remove_all_container

- name: Setup_center
  tags: setup_center
  hosts: center
  vars_files:
    - group_vars/vars.yml
  roles:
    - remove_all_container
    - setup_center

- name: Reset_center
  tags: reset_center
  hosts: center
  roles:
    - remove_all_container

- name: Setup_hb
  tags: setup_hb
  hosts: hb
  vars_files:
    - group_vars/vars.yml
  roles:
    - remove_all_container
    - setup_hb

- name: Reset_hb
  tags: reset_hb
  hosts: hb
  roles:
    - remove_all_container

- name: Setup_trader
  tags: setup_trader
  hosts: trader
  vars_files:
    - group_vars/vars.yml
    - group_vars/trader.yml
    - group_vars/gcloud.yml
  roles:
    - remove_all_container
    - setup_trader

- name: Reset_trader
  tags: reset_trader
  hosts: trader
  roles:
    - remove_all_container
