# code: language=ansible
- name: BASIC
  tags: basic
  vars_files: group_vars/vars.yml
  hosts: all
  roles:
    - basic

- name: REBOOT
  tags: reboot
  hosts: all
  roles:
    - reboot

- name: SETUP TRADER
  tags: setup_trader
  vars_files: group_vars/vars.yml
  hosts: trader
  roles:
    - remove_all_container
    - setup_trader

- name: RESET TRADER
  tags: reset_trader
  vars_files: group_vars/vars.yml
  hosts: trader
  roles:
    - remove_all_container

- name: RESET DB
  tags: reset_db
  vars_files: group_vars/vars.yml
  hosts: center
  roles:
    - reset_db

- name: CENTER SETUP
  tags: setup_center
  vars_files: group_vars/vars.yml
  hosts: center
  roles:
    - remove_all_container
    - setup_center

- name: RESET CENTER
  tags: reset_center
  vars_files: group_vars/vars.yml
  hosts: center
  roles:
    - remove_all_container

- name: BLOG SETUP
  tags: setup_blog
  vars_files: group_vars/vars.yml
  hosts: blog
  roles:
    - remove_all_container
    - basic
    - setup_blog

- name: HB SETUP
  tags: setup_hb
  vars_files: group_vars/vars.yml
  hosts: hb
  roles:
    - remove_all_container
    - basic
    - setup_hb
