# code: language=ansible
- name: Set uptime
  ansible.builtin.command: awk '{print int($1/3600)":"int(($1%3600)/60)":"int($1%60)}' /proc/uptime
  register: uptime
  changed_when: uptime.rc != 0

- name: Show uptime
  ansible.builtin.debug:
    msg: "Uptime: {{ uptime.stdout }}"

- name: Reboot the machine with all defaults
  ansible.builtin.reboot:
