# code: language=ansible
- name: Show OS
  ansible.builtin.debug:
    msg: "Running on OS: {{ ansible_distribution }}"

- name: Setup Debian
  ansible.builtin.include_tasks: setup-debian.yml
  when: ansible_distribution == "Debian"
