# code: language=ansible
- name: Include variables.
  ansible.builtin.include_vars: vars.yml

- name: Create macvlan
  community.docker.docker_network:
    name: "{{ network_name }}"
    state: present
    driver: macvlan
    driver_options: { parent: "{{ network_parent }}" }
    ipam_config:
      - gateway: "172.20.10.1"
        subnet: "172.20.10.0/24"
        iprange: "172.20.10.0/24"

- name: Start node exporter
  community.docker.docker_container:
    name: node-exporter
    image: quay.io/prometheus/node-exporter:latest
    restart_policy: always
    detach: true
    pid_mode: host
    volumes:
      - /:/host:ro,rslave
    command: --path.rootfs=/host
    networks:
      - name: "{{ network_name }}"
        ipv4_address: "{{ ip_node_exporter }}"

- name: Nginx
  block:
    - name: Create config folder
      ansible.builtin.file:
        path: /root/ansible-config/nginx
        state: directory
        mode: 0755

    - name: Configure Nginx
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: /root/ansible-config/nginx/nginx.conf
        mode: 0644

    - name: Start Nginx
      community.docker.docker_container:
        name: nginx
        image: nginx:latest
        restart_policy: always
        detach: true
        volumes:
          - /root/ansible-config/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
          - /root/certbot_data/www:/var/www/certbot/:ro
          - /root/certbot_data/conf:/etc/nginx/ssl/:ro
        networks:
          - name: "{{ network_name }}"
            ipv4_address: "{{ ip_nginx }}"

- name: Rabbitmq
  block:
    - name: Start Rabbitmq
      community.docker.docker_container:
        name: toc-rabbitmq
        image: rabbitmq:3.11.5-management
        restart_policy: always
        detach: true
        env:
          RABBITMQ_DEFAULT_USER: "{{ rabbitmq_user }}"
          RABBITMQ_DEFAULT_PASS: "{{ rabbitmq_password }}"
        networks:
          - name: "{{ network_name }}"
            ipv4_address: "{{ ip_rabbitmq }}"
    - name: Check if is listening
      ansible.builtin.wait_for:
        port: 15672
        delay: 5
        host: "{{ ip_rabbitmq }}"
        timeout: 120

- name: Login Github Container Registry
  community.docker.docker_login:
    registry_url: ghcr.io
    username: "{{ github_user }}"
    password: "{{ github_token }}"
    reauthorize: true

- name: ToC Sinopac Python
  block:
    - name: Configure ToC Sinopac Python
      ansible.builtin.template:
        src: toc_sinopac_python.env.j2
        dest: /root/toc-sinopac-python-env/.env
        mode: 0644

    - name: Start ToC Sinopac Python
      community.docker.docker_container:
        name: toc-sinopac-python
        image: ghcr.io/toc-taiwan/toc-sinopac-python:latest
        restart_policy: always
        detach: true
        volumes:
          - /root/toc-sinopac-python-logs:/toc-sinopac-python/logs
          - /root/toc-sinopac-python-env/.env:/toc-sinopac-python/.env
        env:
          TZ: "Asia/Taipei"
        networks:
          - name: "{{ network_name }}"
            ipv4_address: "{{ ip_toc_sinopac_python }}"

- name: ToC Machine Trading
  block:
    - name: Configure ToC Machine Trading Env
      ansible.builtin.template:
        src: toc_machine_trading.env.j2
        dest: /root/toc-machine-trading-env/.env
        mode: 0644

    - name: Configure ToC Machine Trading Config
      ansible.builtin.template:
        src: toc_machine_trading.yml.j2
        dest: /root/toc-machine-trading-configs/config.yml
        mode: 0644

    - name: Start ToC Machine Trading
      community.docker.docker_container:
        name: toc-machine-trading
        image: ghcr.io/toc-taiwan/toc-machine-trading:latest
        restart_policy: always
        detach: true
        volumes:
          - /root/toc-machine-trading-logs:/toc-machine-trading/logs
          - /root/toc-machine-trading-env/.env:/toc-machine-trading/.env
          - /root/toc-machine-trading-configs/config.yml:/toc-machine-trading/configs/config.yml
        env:
          TZ: "Asia/Taipei"
        networks:
          - name: "{{ network_name }}"
            ipv4_address: "{{ ip_toc_machine_trading }}"
