# code: language=ansible
- name: Create bridge network
  community.docker.docker_network:
    name: "{{ network_name }}"
    force: true
    enable_ipv6: true
    ipam_config:
      - subnet: "172.99.10.0/24"
      - subnet: "fdd0:31ae:44cd:adb2::/64"

- name: Homebridge
  block:
    - name: Create data folder
      ansible.builtin.file:
        path: /root/homebridge-data
        state: directory
        mode: "755"
    - name: Start Homebridge
      community.docker.docker_container:
        name: homebridge
        image: homebridge/homebridge:latest
        restart_policy: always
        detach: true
        ports:
          - "8581:8581"
        volumes:
          - /root/homebridge-data:/homebridge
        env:
          TZ: "Asia/Taipei"
        networks:
          - name: "{{ network_name }}"

    - name: Check if is listening
      ansible.builtin.wait_for:
        port: 8581
        delay: 5
        timeout: 120
