# code: language=ansible
- name: Homebridge
  block:
    - name: Create data folder
      ansible.builtin.file:
        path: /root/homebridge-data
        state: directory
        mode: "755"
    - name: Start Homebridge
      community.docker.docker_container:
        name: homebridge
        image: homebridge/homebridge:latest
        restart_policy: always
        detach: true
        volumes:
          - /root/homebridge-data:/homebridge
        env:
          TZ: "Asia/Taipei"
        networks:
          - name: host

    - name: Check if is listening
      ansible.builtin.wait_for:
        port: 8581
        delay: 5
        timeout: 120
