# code: language=ansible
- name: Remove homebridge
  community.docker.docker_container:
      name: homebridge
      state: absent

- name: Prune everything (including non-dangling images)
  community.docker.docker_prune:
      containers: true
      images: true
      images_filters:
          dangling: false
      networks: true
      volumes: true
      builder_cache: true

- name: Create macvlan
  community.docker.docker_network:
      name: "{{ network_name }}"
      state: present
      driver: macvlan
      driver_options:
          parent: "{{ network_parent }}"
      ipam_config:
          - gateway: "172.20.20.1"
            subnet: "172.20.20.0/24"
            iprange: "172.20.20.0/24"

- name: Configure Docker Daemon
  ansible.builtin.template:
      src: daemon.json.j2
      dest: /etc/docker/daemon.json
      mode: "644"

- name: Reload docker
  ansible.builtin.systemd:
      name: docker
      state: restarted

- name: Homebridge
  block:
      - name: Create data folder
        ansible.builtin.file:
            path: /root/homebridge-data
            state: directory
            mode: "755"
      - name: Start Homebridge
        community.docker.docker_container:
            name: homebridge
            image: homebridge/homebridge:latest
            restart_policy: always
            detach: true
            volumes:
                - /root/homebridge-data:/homebridge
            env:
                TZ: "Asia/Taipei"
            networks:
                - name: "{{ network_name }}"
                  ipv4_address: "{{ ip_hb_homebridge }}"

      - name: Check if is listening
        ansible.builtin.wait_for:
            port: 8581
            delay: 5
            host: "{{ ip_hb_homebridge }}"
            timeout: 120
