all_vm:
    hosts:
        trader:
            ansible_host: 172.20.10.96
        center:
            ansible_host: 172.20.10.99
    vars:
        ansible_user: root

vm_center:
    hosts:
        center:
            ansible_host: 172.20.10.99
    vars:
        ansible_user: root

vm_trader:
    hosts:
        trader:
            ansible_host: 172.20.10.96
    vars:
        ansible_user: root
