# code: language=ansible
- name: Create bridge network
  community.docker.docker_network:
    name: "{{ network_name }}"
    force: true
    enable_ipv6: true
    ipam_config:
      - subnet: "172.99.10.0/24"
      - subnet: "fdd0:31ae:44cd:adb2::/64"

- name: Start DMS
  community.docker.docker_container:
    name: mailserver
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    published_ports:
      - "25:25"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
    hostname: mail.tocraw.com
    auto_remove: true
    detach: true
    env_file: /root/ansible-data/dms/env/mailserver.env
    volumes:
      - /root/ansible-data/dms/mail-data/:/var/mail/
      - /root/ansible-data/dms/mail-state/:/var/mail-state/
      - /root/ansible-data/dms/mail-logs/:/var/log/mail/
      - /root/ansible-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - /root/ansible-data/certbot/conf:/etc/letsencrypt
    networks:
      - name: "{{ network_name }}"

- name: Check if is listening
  ansible.builtin.wait_for:
    port: 587
    delay: 5
    timeout: 120
